### ISSUE TITLE
It does not work for me

### ISSUE THREAD

**Issue by good-repo** [2ocans/Discord-RPC#2]
Hey! Startup problem again.
Can you see if I edited the index correctly?
![screen1](https://user-images.githubusercontent.com/84621585/121793661-6e7b8b00-cc12-11eb-8595-e50bfdaf5bf9.png)

I entered in the Linux terminal
![screen](https://user-images.githubusercontent.com/84621585/121793626-0462e600-cc12-11eb-8604-a8574e73596f.png)

**Comment by 2ocans** [comment]
Hi, Yes, you had successfully modified the index; just make sure you paste your bot's application code beneath "ApplicationID" at the bottom, and your index.js is great to go. The issue is with how you're running the script; make sure you have node installed (https://nodejs.org/en/) before proceeding (Install LTS version). To find out, do node -v in your bash terminal. Make sure it's installed if it isn't already. The second factor is that you must cd into the directory where index.js is placed since the error indicates that index.js cannot be found. So please ensure you're in the correct folder when you execute the command prompt; command: node index.js.

**Comment by 2ocans** [comment]
Example of command to check if node is in fact installed.

![node -v](https://user-images.githubusercontent.com/73264796/121809524-18671180-cc2b-11eb-89be-773d85eff440.JPG)

Example of node command and how to cd to folder. 
![Node command](https://user-images.githubusercontent.com/73264796/121809674-b3f88200-cc2b-11eb-8f14-95bd32dfe4f3.JPG)
